# https://travis-ci.org/candango/firenado
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements/basic.txt"
  - "pip install -r requirements/redis.txt"
  - "pip install -r requirements/sqlalchemy.txt"
script:
  - "PYTHONPATH=$PYTHONPATH:. python tests/runtests.py"
