# https://travis-ci.org/candango/firenado
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -r requirements/basic.txt"
  - "pip install -r requirements/all.txt"
  - "pip install -r requirements/tests.txt"
  - "python setup.py install"
script:
  - "PYTHONPATH=$PYTHONPATH:. python tests/runtests.py"
  - behave tests/features
